# packages in environment at /Users/danielye/miniforge3/envs/cluster_ass_1:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h620ffc9_4  
ca-certificates           2022.3.29            hca03da5_0  
certifi                   2021.10.8        py38hca03da5_2  
geos                      3.9.1                hc377ac9_1  
libblas                   3.9.0           11_osxarm64_openblas    conda-forge
libcblas                  3.9.0           11_osxarm64_openblas    conda-forge
libcxx                    12.0.0               hf6beb65_1  
libffi                    3.4.2                hc377ac9_2  
libgfortran               5.0.0           11_1_0_h6a59814_26  
libgfortran5              11.1.0              h6a59814_26  
liblapack                 3.9.0           11_osxarm64_openblas    conda-forge
libopenblas               0.3.17               hea475bc_1  
libzlib                   1.2.11            h90dfc92_1014    conda-forge
llvm-openmp               12.0.0               haf9daa7_1  
mpi                       1.0                     openmpi  
mpi4py                    3.1.3            py38hbcaf744_0    conda-forge
ncurses                   6.3                  h1a28f6b_2  
numpy                     1.19.5           py38heec5a64_2  
openmpi                   4.1.1                h840aa90_1  
openssl                   1.1.1n               h1a28f6b_0  
pip                       21.2.4           py38hca03da5_0  
python                    3.8.13          h7e095e3_0_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1.2                h1a28f6b_1  
setuptools                58.0.4           py38hca03da5_1  
shapely                   1.7.1            py38h18ef730_5  
sqlite                    3.38.2               h1058600_0  
tk                        8.6.12               he1e0b03_0    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h1a28f6b_0  
zlib                      1.2.11            h90dfc92_1014    conda-forge
